# values for versions are: lastest, major, specific
# Lastest it's for lastest published stable version
# Major it's for the lastest publish of a major version. "Version" must specify the major version, "1", "2" for instance
# Specific it's for a specific version. For example "1.2.15". The version field must specify this version
nvidia-gpu-ori:
    enable: True
    cuda_completeversion: 10.2.89
    cuda_major_version: 10-2
    cuda_Major_version_with_dot: 10.2
    # cuDNN version can be found in 6.1.1 there:
    # https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
    dpkg: 7
    cudnn_version: 7.6.5.32-1
    # TensortRT version can be found in 4.1 point 3 there:
    # https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
    tensortrt_version: 7.6.5.32-1
    libnvinfer_version: 7
nvidia-gpu:
    enable: True
    params:
        # Change only this one for change CUDA version
        CUDA_VERSION: 10.2
    # Do not change following versions. Only if you know what you're doing
    # ------- CUDA 10.2
    cuda_version_10.2: 10.2.89
    cuda_major_version_10.2: 10-2
    cuda_Major_version_with_dot_10.2: 10.2
    # cuDNN version can be found in 6.1.1 there:
    # https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
    cudnn_major_version_10.2: 7
    cudnn_version_10.2: 7.6.5.32-1
    # TensortRT version can be found in 4.1 point 3 there:
    # https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
    tensortrt_version_10.2: 7.0.0-1
    libnvinfer_version_10.2: 7    
    # ------- CUDA 10.2
    cuda_version_10.1: 10.1.168
    cuda_major_version_10.1: 10-1
    cuda_Major_version_with_dot_10.1: 10.1
    # cuDNN version can be found in 6.1.1 there:
    # https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
    cudnn_major_version_10.1: 7
    cudnn_version_10.1: 7.6.4.38-1
    # TensortRT version can be found in 4.1 point 3 there:
    # https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
    tensortrt_version_10.1: 6.0.1-1
    libnvinfer_version_10.1: 6    
    
tensorflow:
    type_version: lastest
    version: 1
opencv:
    type_version: lastest
    version: 3
object_detection:
    enable: True
    command_install_ssd_mobilenet_v1_coco: False
    command_install_ssd_mobilenet_v1_0.75_depth_coco: False
    command_install_ssd_mobilenet_v1_quantized_coco: False
    command_install_ssd_mobilenet_v1_0.75_depth_quantized_coco: False
    command_install_ssd_mobilenet_v1_ppn_coco: False
    command_install_ssd_mobilenet_v1_fpn_coco: False
    command_install_ssd_resnet_50_fpn_coco: False
    command_install_ssd_mobilenet_v2_coco: True
    command_install_ssd_mobilenet_v2_quantized_coco: False
    command_install_ssdlite_mobilenet_v2_coco: False
    command_install_ssd_inception_v2_coco: True
    command_install_faster_rcnn_inception_v2_coco: True
    command_install_faster_rcnn_resnet50_coco: False
    command_install_faster_rcnn_resnet50_lowproposals_coco: False
    command_install_rfcn_resnet101_coco: False
    command_install_faster_rcnn_resnet101_coco: False
    command_install_faster_rcnn_resnet101_lowproposals_coco: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_coco: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco: False
    command_install_faster_rcnn_nas: False
    command_install_faster_rcnn_nas_lowproposals_coco: False
    command_install_mask_rcnn_inception_resnet_v2_atrous_coco: False
    command_install_mask_rcnn_inception_v2_coco: False
    command_install_mask_rcnn_resnet101_atrous_coco: False
    command_install_mask_rcnn_resnet50_atrous_coco: False
    command_install_ssd_mobilenet_v3_large_coco: False
    command_install_ssd_mobilenet_v3_small_coco: False
    command_install_ssd_mobilenet_edgetpu_coco: False
    command_install_faster_rcnn_resnet101_kitti: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv2: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_oidv2: False
    command_install_facessd_mobilenet_v2_quantized_open_image_v4: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv4: False
    command_install_ssd_mobilenetv2_oidv4: False
    command_install_ssd_resnet_101_fpn_oidv4: False
    command_install_faster_rcnn_resnet101_fgvc: False
    command_install_faster_rcnn_resnet50_fgvc: False
    command_install_faster_rcnn_resnet101_ava_v2.1: False
    command_install_faster_rcnn_resnet101_lowproposals_coco: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_coco: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco: False
    command_install_faster_rcnn_nas: False
    command_install_faster_rcnn_nas_lowproposals_coco: False
    command_install_mask_rcnn_inception_resnet_v2_atrous_coco: False
    command_install_mask_rcnn_inception_v2_coco: False
    command_install_mask_rcnn_resnet101_atrous_coco: False
    command_install_mask_rcnn_resnet50_atrous_coco: False
    command_install_ssd_mobilenet_v3_large_coco: False
    command_install_ssd_mobilenet_v3_small_coco: False
    command_install_ssd_mobilenet_edgetpu_coco: False
    command_install_faster_rcnn_resnet101_kitti: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv2: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_oidv2: False
    command_install_facessd_mobilenet_v2_quantized_open_image_v4: False
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv4: False
    command_install_ssd_mobilenetv2_oidv4: False
    command_install_ssd_resnet_101_fpn_oidv4: False
    command_install_faster_rcnn_resnet101_fgvc: False
    command_install_faster_rcnn_resnet50_fgvc: False
    command_install_faster_rcnn_resnet101_ava_v2.1: False