nvidia-gpu:
    # From Nvidia (https://gitlab.com/nvidia/container-images/cuda/)
    command_install: > 
        USER root

        RUN apt update && apt install -y --no-install-recommends gnupg2 curl ca-certificates && \
            curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - && \
            echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
            echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
            apt purge --autoremove -y curl && \
            rm -rf /var/lib/apt/lists/*

        ENV CUDA_VERSION {nvidia-gpu_cuda_version_{CUDA_VERSION}}

        ENV CUDA_PKG_VERSION {nvidia-gpu_cuda_major_version_{CUDA_VERSION}}=$CUDA_VERSION-1


        # For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a

        RUN apt update && apt install -y --no-install-recommends \
            cuda-cudart-$CUDA_PKG_VERSION \
            cuda-compat-{nvidia-gpu_cuda_major_version_{CUDA_VERSION}} && \
            ln -s cuda-{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} /usr/local/cuda && \
            ln -s /usr/local/cuda-{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}}/targets/x86_64-linux/lib/libcudart.so.{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} /usr/local/lib/libcudart.so.10.1 && \
            rm -rf /var/lib/apt/lists/*


        # Required for nvidia-docker v1

        RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
            echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

        ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
        
        ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64


        # nvidia-container-runtime

        ENV NVIDIA_VISIBLE_DEVICES all

        ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

        ENV NVIDIA_REQUIRE_CUDA "cuda>={nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419"

        # Tensorflow Options

        ENV OPTION_CUDA "--config=cuda"

    cuda_install: >
        # Add NVIDIA package repositories
        
        # From https://www.tensorflow.org/install/gpu
        
        RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_{nvidia-gpu_cuda_version_{CUDA_VERSION}}-1_amd64.deb && \
            apt install -y -o Dpkg::Options::="--force-confold" ./cuda-repo-ubuntu1804_{nvidia-gpu_cuda_version_{CUDA_VERSION}}-1_amd64.deb && \
            apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
            apt update && \
            wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
            apt install -y ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
            apt update

        
        # Install NVIDIA driver
        
        # Install development and runtime libraries (~4GB)
        # cuDNN version can be found in 6.1.1 there:
        # https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
        
        RUN apt install -y --no-install-recommends \
            # Replace cuda by cuda-toolkit. Cuda raises some unresolved dependences
            # cuda-10-1 \
            cuda-toolkit-{nvidia-gpu_cuda_major_version_{CUDA_VERSION}} \
            libcudnn{nvidia-gpu_cudnn_major_version_{CUDA_VERSION}}={nvidia-gpu_cudnn_version_{CUDA_VERSION}}+cuda{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}}  \
            libcudnn{nvidia-gpu_cudnn_major_version_{CUDA_VERSION}}-dev={nvidia-gpu_cudnn_version_{CUDA_VERSION}}+cuda{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} 


        # Install TensorRT. Requires that libcudnn7 is installed above.
        # TensortRT version can be found in 4.1 point 3 there:
        # https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
        
        RUN apt install -y --no-install-recommends libnvinfer{nvidia-gpu_libnvinfer_version_{CUDA_VERSION}}={nvidia-gpu_tensortrt_version_{CUDA_VERSION}}+cuda{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} \
            libnvinfer-dev={nvidia-gpu_tensortrt_version_{CUDA_VERSION}}+cuda{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} \
            libnvinfer-plugin{nvidia-gpu_libnvinfer_version_{CUDA_VERSION}}={nvidia-gpu_tensortrt_version_{CUDA_VERSION}}+cuda{nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}} && \
            apt clean && rm -rf /var/lib/apt/lists/*

        ENV PYTORCH_CUDA_INSTALL cudatoolkit={nvidia-gpu_cuda_Major_version_with_dot_{CUDA_VERSION}}

        USER $NB_USER
tensorflow:
    command_install: >
        # Installation of tensorflow

        RUN cd /home/icare/libs &&  \
            strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC && \
            export LD_LIBRARY_PATH=/usr/local/lib64  && \
            git clone https://github.com/bazelbuild/bazelisk.git && \
            ln bazelisk/bazelisk.py bazelisk/bazel && \
            export PATH=$PATH:/home/icare/libs/bazelisk && \
            conda install pip six numpy<1.19.0 wheel setuptools mock 'future>=0.17.1' && \
            pip install -U keras_applications --no-deps && \
            pip install -U keras_preprocessing --no-deps && \
            cd /home/icare/libs && \
            git clone https://github.com/tensorflow/tensorflow.git && \
            cd tensorflow && \
            git checkout r{tensorflow_version} && \
            ./configure && \
            bazel build --config=v2 $OPTION_CUDA //tensorflow/tools/pip_package:build_pip_package && \
            ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg && \
            pip install /tmp/tensorflow_pkg/tensorflow-{tensorflow_version}*.whl && \
            bazel clean --expunge

opencv:
    command_user_to_root: > 
        USER root


        RUN apt update && \
            apt install -y cmake unzip pkg-config libjpeg-dev libpng-dev libtiff-dev libavcodec-dev  \
                          libxvidcore-dev libx264-dev libgtk-3-dev libatlas-base-dev gfortran python3-dev && \
            apt clean && rm -rf /var/lib/apt/lists/*
    command_install: >
        RUN wget -q -O $DL_LIBS/opencv.zip https://github.com/opencv/opencv/archive/{opencv_version}.zip && \ 
            wget -q -O $DL_LIBS/opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/{opencv_version}.zip && \
            unzip $DL_LIBS/opencv.zip -d $DL_LIBS && \
            unzip $DL_LIBS/opencv_contrib.zip -d $DL_LIBS && \
            rm -rf $DL_LIBS/*.zip && \
            mv $DL_LIBS/opencv-* $DL_LIBS/opencv && \
            mv $DL_LIBS/opencv_contrib* $DL_LIBS/opencv_contrib && \
            mkdir $DL_LIBS/opencv/build && \
            cd $DL_LIBS/opencv/build && \
            cmake -D WITH_CUDA=OFF \
                -D BUILD_TIFF=ON \
                -D BUILD_opencv_java=OFF \
                -D ENABLE_AVX=ON \
                -D WITH_OPENGL=ON \
                -D WITH_OPENCL=ON \
                -D WITH_IPP=ON \
                -D WITH_TBB=ON \
                -D WITH_EIGEN=ON \
                -D WITH_V4L=ON \
                -D WITH_VTK=OFF \
                -D BUILD_TESTS=OFF \
                -D BUILD_PERF_TESTS=OFF \
                -D CMAKE_BUILD_TYPE=RELEASE \
                -D BUILD_opencv_python2=OFF \
                -D CMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") \
                -D PYTHON3_EXECUTABLE=$(which python3) \
                -D PYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
                -D PYTHON3_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \
                -D CMAKE_BUILD_TYPE=RELEASE \
                -D CMAKE_INSTALL_PREFIX=$DL_LIBS \
                -D PYTHON_DEFAULT_EXECUTABLE=$(which python3) \ 
                -D OPENCV_EXTRA_MODULES_PATH=$DL_LIBS/opencv_contrib/modules \
                -D BUILD_EXAMPLES=ON .. && \
            make -j4 && make install && ldconfig  && make clean && \
            # Experience some issues with libfreetype library
            # There is already in system path
            # More infos:
            # https://rtbecard.gitlab.io/2018/11/03/Installing-opencv-with-ffmpeg-support-in-Anaconda3-(Ubuntu-16.04).html
            rm -rf $CONDA_DIR/lib/libfontconfig.* \
            rm -rf $CONDA_DIR/lib/libgio-2.0.so* \        
            set PATH=$PATH:$DL_LIBS\bin && \
            fix-permissions $DL_LIBS         
        
        USER $NB_USER
object_detection:
    command_user_to_root: USER root
    command_install: >
        RUN pip install Cython contextlib2 pillow lxml protobuf protobuf-compiler pycocotools && \
            mkdir -p $DL_LIBS/tensorflow && \ 
            cd $DL_LIBS/tensorflow && \ 
            git clone https://github.com/tensorflow/models.git && \
            set PYTHONPATH=$DL_LIBS/tensorflow/models:$DL_LIBS/tensorflow/models/research:$DL_LIBS/tensorflow/models/research/slim:$PYTHONPATH && \
            cd $DL_LIBS/tensorflow/models/research && \
            protoc object_detection/protos/*.proto --python_out=. && \
            python setup.py build && \
            python setup.py install  && \
            fix-permissions $DL_LIBS/tensorflow      
    command_install_ssd_mobilenet_v1_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz && \
            tar xvzf ssd_mobilenet_v1_coco_2018_01_28.tar.gz && \
            rm ssd_mobilenet_v1_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v1_0.75_depth_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03.tar.gz && \
            tar xvzf ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03.tar.gz && \
            rm ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v1_quantized_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz && \
            tar xvzf ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz && \
            rm ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v1_0.75_depth_quantized_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18.tar.gz && \
            tar xvzf ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18.tar.gz && \
            rm ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v1_ppn_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03.tar.gz && \
            tar xvzf ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03 && \
            rm ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03 
    command_install_ssd_mobilenet_v1_fpn_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
            tar xvzf ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
            rm ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_resnet_50_fpn_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
            tar xvzf ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
            rm ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v2_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz && \
            tar xvzf ssd_mobilenet_v2_coco_2018_03_29.tar.gz && \
            rm ssd_mobilenet_v2_coco_2018_03_29.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v2_quantized_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz && \
            tar xvzf ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz && \
            rm ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssdlite_mobilenet_v2_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz && \
            tar xvzf ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz && \
            rm ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_inception_v2_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz && \
            tar xvzf ssd_inception_v2_coco_2018_01_28.tar.gz && \
            rm ssd_inception_v2_coco_2018_01_28.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_v2_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_inception_v2_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_inception_v2_coco_2018_01_28.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet50_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_resnet50_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_resnet50_coco_2018_01_28.tar.gz  && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet50_lowproposals_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_lowproposals_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_resnet50_lowproposals_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_resnet50_lowproposals_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_rfcn_resnet101_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/rfcn_resnet101_coco_2018_01_28.tar.gz && \
            tar xvzf rfcn_resnet101_coco_2018_01_28.tar.gz && \
            rm rfcn_resnet101_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet101_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_resnet101_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_resnet101_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet101_lowproposals_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_lowproposals_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_resnet101_lowproposals_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_resnet101_lowproposals_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_resnet_v2_atrous_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_nas: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_nas_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_nas_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_nas_lowproposals_coco: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_lowproposals_coco_2018_01_28.tar.gz && \
            tar xvzf faster_rcnn_nas_lowproposals_coco_2018_01_28.tar.gz && \
            rm faster_rcnn_nas_lowproposals_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_mask_rcnn_inception_resnet_v2_atrous_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            tar xvzf mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            rm mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_mask_rcnn_inception_v2_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/mask_rcnn_inception_v2_coco_2018_01_28.tar.gz && \
            tar xvzf mask_rcnn_inception_v2_coco_2018_01_28.tar.gz && \
            rm mask_rcnn_inception_v2_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_mask_rcnn_resnet101_atrous_coco: >
        RUN cd $DL_LIBS/tensorflow && \
            wget http://download.tensorflow.org/models/object_detection/mask_rcnn_resnet101_atrous_coco_2018_01_28.tar.gz && \
            tar xvzf mask_rcnn_resnet101_atrous_coco_2018_01_28.tar.gz && \
            rm mask_rcnn_resnet101_atrous_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_mask_rcnn_resnet50_atrous_coco: >
        RUN wget http://download.tensorflow.org/models/object_detection/mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz && \
            tar xvzf mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz && \
            rm mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v3_large_coco: >
        RUN wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_large_coco_2019_08_14.tar.gz && \
            tar ssd_mobilenet_v3_large_coco_2019_08_14.tar.gz && \
            rm ssd_mobilenet_v3_large_coco_2019_08_14.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_v3_small_coco: >
        RUN wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz && \
            tar ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz && \
            rm ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenet_edgetpu_coco: >
        RUN wget https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/ssdlite_mobilenet_edgetpu_coco_quant.tar.gz && \
            tar ssdlite_mobilenet_edgetpu_coco_quant.tar.gz && \
            rm ssdlite_mobilenet_edgetpu_coco_quant.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet101_kitti: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_kitti_2018_01_28.tar.gz && \
            tar faster_rcnn_resnet101_kitti_2018_01_28.tar.gz && \
            rm faster_rcnn_resnet101_kitti_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv2: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28.tar.gz && \
            tar ssd_faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28.tar.gz && \
            rm faster_rcnn_inception_resnet_v2_atrous_oid_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_resnet_v2_atrous_lowproposals_oidv2: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid_2018_01_28.tar.gz && \
            tar faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid_2018_01_28.tar.gz && \
            rm faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid_2018_01_28.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_facessd_mobilenet_v2_quantized_open_image_v4: >
        RUN wget http://download.tensorflow.org/models/object_detection/facessd_mobilenet_v2_quantized_320x320_open_image_v4.tar.gz && \
            tar facessd_mobilenet_v2_quantized_320x320_open_image_v4.tar.gz && \
            rm facessd_mobilenet_v2_quantized_320x320_open_image_v4.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_inception_resnet_v2_atrous_oidv4: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_oid_v4_2018_12_12.tar.gz && \
            tar faster_rcnn_inception_resnet_v2_atrous_oid_v4_2018_12_12.tar.gz && \
            rm faster_rcnn_inception_resnet_v2_atrous_oid_v4_2018_12_12.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_mobilenetv2_oidv4: >
        RUN wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_oid_v4_2018_12_12.tar.gz && \
            tar ssd_mobilenet_v2_oid_v4_2018_12_12.tar.gz && \
            rm ssd_mobilenet_v2_oid_v4_2018_12_12.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_ssd_resnet_101_fpn_oidv4: >
        RUN wget http://download.tensorflow.org/models/object_detection/ssd_resnet101_v1_fpn_shared_box_predictor_oid_512x512_sync_2019_01_20.tar.gz && \
            tar ssd_resnet101_v1_fpn_shared_box_predictor_oid_512x512_sync_2019_01_20.tar.gz && \
            rm ssd_resnet101_v1_fpn_shared_box_predictor_oid_512x512_sync_2019_01_20.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet101_fgvc: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_fgvc_2018_07_19.tar.gz && \
            tar faster_rcnn_resnet101_fgvc_2018_07_19.tar.gz && \
            rm faster_rcnn_resnet101_fgvc_2018_07_19.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet50_fgvc: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_fgvc_2018_07_19.tar.gz && \
            tar faster_rcnn_resnet50_fgvc_2018_07_19.tar.gz && \
            rm faster_rcnn_resnet50_fgvc_2018_07_19.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_install_faster_rcnn_resnet101_ava_v2.1: >
        RUN wget http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_ava_v2.1_2018_04_30.tar.gz && \
            tar faster_rcnn_resnet101_ava_v2.1_2018_04_30.tar.gz && \
            rm faster_rcnn_resnet101_ava_v2.1_2018_04_30.tar.gz && \
            fix-permissions $DL_LIBS/tensorflow
    command_user_to_personnal: USER $NB_USER

torchvision:
    command_version_install: >
        ENV TORCHVISION_INSTALL_COMMAND torchvision=={torchvision_version}

pytorch:
    command_install: >
        USER root
        
        RUN conda install  pytorch=={pytorch_version} $TORCHVISION_INSTALL_COMMAND $PYTORCH_CUDA_INSTALL -c pytorch

        USER $NB_USER



